# Generated by Django 5.1.4 on 2024-12-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('employee_count', models.IntegerField(verbose_name='Количество сотрудников')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('access_level', models.CharField(choices=[('admin', 'Админ'), ('moderator', 'Модератор')], max_length=50, verbose_name='Уровень доступа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='company.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company', verbose_name='Компания')),
            ],
        ),
    ]
