# Generated by Django 5.1.4 on 2024-12-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи запроса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='company.company', verbose_name='Компания')),
            ],
        ),
    ]
